dist: xenial
language: python
python:
  - "3.7"

install:
  pip install pylint pylint-exit

jobs:
  include:
    - stage: lint
      script:
        # convert the exit code from pylint into a standard error code
        pylint main.py || pylint-exit $?

    - stage: test
      script:
        # run unit tests
        python -m unittest -v

notifications:
  slack:
    rooms:
      - deans-group-hq:j0qLDOwvvpw4S4nQRp0NJeUT
      - deans-group-hq:j0qLDOwvvpw4S4nQRp0NJeUT#travis