dist: xenial
language: python
python:
  - "3.7"

script:
  python3 main.py

notifications:
  slack:
    rooms:
      - deans-group-hq:j0qLDOwvvpw4S4nQRp0NJeUT
      - deans-group-hq:j0qLDOwvvpw4S4nQRp0NJeUT#travis