dist: xenial
language: python
python:
  - "3.7"

install:
  pip install pylint

script:
  pylint main.py

notifications:
  slack:
    rooms:
      - deans-group-hq:j0qLDOwvvpw4S4nQRp0NJeUT
      - deans-group-hq:j0qLDOwvvpw4S4nQRp0NJeUT#travis